#### https://www.benkuhn.net/tree-imp

In [227]:


def round_to_nearest_zero_point_five(inp):
    return (inp*2).round()/2

def round_to_nearest_zero_point_two_five(inp):
    return (inp*4).round()/4

In [228]:
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn import datasets
import numpy as np

iris=datasets.load_iris()
X = iris.data
y = iris.target.reshape(1,150)

data = np.concatenate((X, y.T), axis=1)

#data = data.round()
#data = round_to_nearest_zero_point_five(data)
data = round_to_nearest_zero_point_two_five(data)


data_train, data_test = train_test_split(data, test_size=0.25, random_state=33)
print("Training data:\n", data_train)
print("Testing data:\n", data_test)

Training data:
 [[5.   2.25 3.25 1.   1.  ]
 [5.   3.   1.5  0.25 0.  ]
 [6.25 2.25 4.5  1.25 1.  ]
 [5.75 2.5  4.   1.25 1.  ]
 [6.25 3.   4.25 1.25 1.  ]
 [4.75 3.25 1.25 0.25 0.  ]
 [4.5  3.5  1.5  0.25 0.  ]
 [5.   2.5  3.   1.   1.  ]
 [4.75 3.5  1.5  0.25 0.  ]
 [8.   3.75 6.5  2.   2.  ]
 [5.   3.5  1.5  0.25 0.  ]
 [5.   3.75 1.5  0.5  0.  ]
 [5.5  3.   3.5  1.25 1.  ]
 [6.5  3.   5.5  1.75 2.  ]
 [5.5  4.   1.75 0.5  0.  ]
 [7.   3.25 4.75 1.5  1.  ]
 [5.75 2.75 5.   2.5  2.  ]
 [7.75 2.5  7.   2.25 2.  ]
 [5.5  2.5  4.   1.25 1.  ]
 [6.   3.25 4.75 1.75 1.  ]
 [5.   3.5  1.5  0.   0.  ]
 [4.5  2.25 1.25 0.25 0.  ]
 [6.25 2.75 5.   1.5  2.  ]
 [4.5  3.   1.5  0.25 0.  ]
 [5.   3.5  1.5  0.25 0.  ]
 [7.25 3.   5.75 1.5  2.  ]
 [6.   3.5  4.5  1.5  1.  ]
 [6.25 2.25 4.5  1.5  1.  ]
 [7.5  2.75 6.   2.   2.  ]
 [6.75 3.   5.5  2.   2.  ]
 [6.5  2.75 5.5  2.25 2.  ]
 [5.75 2.5  5.   2.   2.  ]
 [5.   3.5  1.5  0.5  0.  ]
 [5.   3.75 1.5  0.25 0.  ]
 [6.75 2.75 4.75 1.5  1.  ]
 [5.

In [229]:
header = iris.feature_names
header

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [230]:
def unique_values(rows, col):
    """Find the unique values for a column in a dataset."""
    return set([row[col] for row in rows])

In [231]:
unique_values(data_train, 1)

{2.0, 2.25, 2.5, 2.75, 3.0, 3.25, 3.5, 3.75, 4.0, 4.25, 4.5}

In [232]:
def class_counts(rows):
    """Counts the number of each type of example in a dataset."""
    counts = {}  # a dictionary of label -> count.
    for row in rows:
        # in our dataset format, the label is always the last column
        label = row[-1]
        if label not in counts:
            counts[label] = 0
        counts[label] += 1
    return counts

In [233]:
class Question:
    """A Question is used to partition a dataset.

    This class just records a 'column number' (e.g., 0 for Color) and a
    'column value' (e.g., Green). The 'match' method is used to compare
    the feature value in an example to the feature value stored in the
    question. See the demo below.
    """

    def __init__(self, column, value):
        self.column = column
        self.value = value

    def match(self, example):
        # Compare the feature value in an example to the
        # feature value in this question.
        val = example[self.column]
        return val >= self.value

    def __repr__(self):
        # This is just a helper method to print
        # the question in a readable format.
        condition = ">="
        return "Is %s %s %s?" % (
            header[self.column], condition, str(self.value))

In [234]:
Question(1, 2)


Is sepal width (cm) >= 2?

In [235]:
def partition(rows, question):
    """Partitions a dataset.

    For each row in the dataset, check if it matches the question. If
    so, add it to 'true rows', otherwise, add it to 'false rows'.
    """
    true_rows, false_rows = [], []
    for row in rows:
        if question.match(row):
            true_rows.append(row)
        else:
            false_rows.append(row)
    return true_rows, false_rows

In [236]:
true_rows, false_rows = partition(data_train, Question(0, 1))

In [237]:
true_rows

[array([5.  , 2.25, 3.25, 1.  , 1.  ]),
 array([5.  , 3.  , 1.5 , 0.25, 0.  ]),
 array([6.25, 2.25, 4.5 , 1.25, 1.  ]),
 array([5.75, 2.5 , 4.  , 1.25, 1.  ]),
 array([6.25, 3.  , 4.25, 1.25, 1.  ]),
 array([4.75, 3.25, 1.25, 0.25, 0.  ]),
 array([4.5 , 3.5 , 1.5 , 0.25, 0.  ]),
 array([5. , 2.5, 3. , 1. , 1. ]),
 array([4.75, 3.5 , 1.5 , 0.25, 0.  ]),
 array([8.  , 3.75, 6.5 , 2.  , 2.  ]),
 array([5.  , 3.5 , 1.5 , 0.25, 0.  ]),
 array([5.  , 3.75, 1.5 , 0.5 , 0.  ]),
 array([5.5 , 3.  , 3.5 , 1.25, 1.  ]),
 array([6.5 , 3.  , 5.5 , 1.75, 2.  ]),
 array([5.5 , 4.  , 1.75, 0.5 , 0.  ]),
 array([7.  , 3.25, 4.75, 1.5 , 1.  ]),
 array([5.75, 2.75, 5.  , 2.5 , 2.  ]),
 array([7.75, 2.5 , 7.  , 2.25, 2.  ]),
 array([5.5 , 2.5 , 4.  , 1.25, 1.  ]),
 array([6.  , 3.25, 4.75, 1.75, 1.  ]),
 array([5. , 3.5, 1.5, 0. , 0. ]),
 array([4.5 , 2.25, 1.25, 0.25, 0.  ]),
 array([6.25, 2.75, 5.  , 1.5 , 2.  ]),
 array([4.5 , 3.  , 1.5 , 0.25, 0.  ]),
 array([5.  , 3.5 , 1.5 , 0.25, 0.  ]),
 array([7.

In [238]:
false_rows

[]

In [239]:
def gini(rows):
    """Calculate the Gini Impurity for a list of rows.

    There are a few different ways to do this, I thought this one was
    the most concise. See:
    https://en.wikipedia.org/wiki/Decision_tree_learning#Gini_impurity
    """
    counts = class_counts(rows)
    impurity = 1
    for lbl in counts:
        prob_of_lbl = counts[lbl] / float(len(rows))
        impurity -= prob_of_lbl**2
    return impurity

In [240]:
gini([[1],[2],[2],[1],[3]])

0.6399999999999999

In [241]:
def info_gain(left, right, current_uncertainty):
    """Information Gain.

    The uncertainty of the starting node, minus the weighted impurity of
    two child nodes.
    """
    p = float(len(left)) / (len(left) + len(right))
    return current_uncertainty - p * gini(left) - (1 - p) * gini(right)

In [242]:
current_uncertainty = gini(data_train)
true_rows, false_rows = partition(data_train, Question(0,7))
info_gain(true_rows, false_rows, current_uncertainty)

0.07423013848396498

In [243]:
def find_best_split(rows):
    """Find the best question to ask by iterating over every feature / value
    and calculating the information gain."""
    best_gain = 0  # keep track of the best information gain
    best_question = None  # keep train of the feature / value that produced it
    current_uncertainty = gini(rows)
    n_features = len(rows[0]) - 1  # number of columns

    for col in range(n_features):  # for each feature

        values = set([row[col] for row in rows])  # unique values in the column

        for val in values:  # for each value

            question = Question(col, val)

            # try splitting the dataset
            true_rows, false_rows = partition(rows, question)

            # Skip this split if it doesn't divide the
            # dataset.
            if len(true_rows) == 0 or len(false_rows) == 0:
                continue

            # Calculate the information gain from this split
            gain = info_gain(true_rows, false_rows, current_uncertainty)

            # You actually can use '>' instead of '>=' here
            # but I wanted the tree to look a certain way for our
            # toy dataset.
            if gain >= best_gain:
                best_gain, best_question = gain, question

    return best_gain, best_question

In [244]:
best_gain, best_question = find_best_split(data_train)
print("Best gain: ", best_gain, 
      "\nbest question: ", best_question)

Best gain:  0.35309311224489803 
best question:  Is petal width (cm) >= 1.0?


In [245]:
class Leaf:
    """A Leaf node classifies data.

    This holds a dictionary of class (e.g., "Apple") -> number of times
    it appears in the rows from the training data that reach this leaf.
    """

    def __init__(self, rows):
        self.predictions = class_counts(rows)

In [260]:
class Decision_Node:
    """A Decision Node asks a question.

    This holds a reference to the question, and to the two child nodes.
    """

    def __init__(self, question, true_branch, false_branch):
        self.question = question
        self.true_branch = true_branch
        self.false_branch = false_branch

In [247]:
def build_tree(rows):
    """Builds the tree.

    Rules of recursion: 1) Believe that it works. 2) Start by checking
    for the base case (no further information gain). 3) Prepare for
    giant stack traces.
    """

    # Try partitioing the dataset on each of the unique attribute,
    # calculate the information gain,
    # and return the question that produces the highest gain.
    gain, question = find_best_split(rows)

    # Base case: no further info gain
    # Since we can ask no further questions,
    # we'll return a leaf.
    if gain == 0:
        return Leaf(rows)

    # If we reach here, we have found a useful feature / value
    # to partition on.
    true_rows, false_rows = partition(rows, question)

    # Recursively build the true branch.
    true_branch = build_tree(true_rows)

    # Recursively build the false branch.
    false_branch = build_tree(false_rows)

    # Return a Question node.
    # This records the best feature / value to ask at this point,
    # as well as the branches to follow
    # dependingo on the answer.
    return Decision_Node(question, true_branch, false_branch)

In [248]:
def print_tree(node, spacing=""):
    """World's most elegant tree printing function."""

    # Base case: we've reached a leaf
    if isinstance(node, Leaf):
        print (spacing + "Predict", node.predictions)
        return

    # Print the question at this node
    print (spacing + str(node.question))

    # Call this function recursively on the true branch
    print (spacing + '--> True:')
    print_tree(node.true_branch, spacing + "  ")

    # Call this function recursively on the false branch
    print (spacing + '--> False:')
    print_tree(node.false_branch, spacing + "  ")

In [249]:
my_tree = build_tree(data_train)
print_tree(my_tree)

Is petal width (cm) >= 1.0?
--> True:
  Is petal width (cm) >= 1.75?
  --> True:
    Is petal length (cm) >= 5.0?
    --> True:
      Is petal width (cm) >= 2.0?
      --> True:
        Predict {2.0: 22}
      --> False:
        Is sepal length (cm) >= 6.75?
        --> True:
          Is petal length (cm) >= 5.75?
          --> True:
            Predict {2.0: 2}
          --> False:
            Predict {1.0: 1}
        --> False:
          Predict {2.0: 4}
    --> False:
      Is petal length (cm) >= 4.75?
      --> True:
        Predict {1.0: 1}
      --> False:
        Predict {2.0: 1}
  --> False:
    Is petal length (cm) >= 5.75?
    --> True:
      Predict {2.0: 1}
    --> False:
      Is petal length (cm) >= 5.0?
      --> True:
        Is sepal width (cm) >= 2.75?
        --> True:
          Is sepal length (cm) >= 6.25?
          --> True:
            Is sepal width (cm) >= 3.0?
            --> True:
              Predict {1.0: 1}
            --> False:
              Predict {

In [250]:
def classify(row, node):
    """See the 'rules of recursion' above."""

    # Base case: we've reached a leaf
    if isinstance(node, Leaf):
        return node.predictions

    # Decide whether to follow the true-branch or the false-branch.
    # Compare the feature / value stored in the node,
    # to the example we're considering.
    if node.question.match(row):
        return classify(row, node.true_branch)
    else:
        return classify(row, node.false_branch)

In [251]:
classify(data_train[0],my_tree)

{1.0: 34}

In [256]:
def print_leaf(counts):
    total = sum(counts.values())
    probs = {}
    for lbl in counts.keys():
        probs[lbl] = str(int(counts[lbl] / total * 100)) + "%"
    return probs

In [257]:
print_leaf(classify(data_train[0], my_tree))

{1.0: '100%'}

In [258]:
print_leaf(classify(data_train[18], my_tree))

{1.0: '100%'}

In [259]:
for row in data_test:
    print ("Actual: %s. Predicted: %s" %
           (row[-1], print_leaf(classify(row, my_tree))))

Actual: 1.0. Predicted: {1.0: '100%'}
Actual: 1.0. Predicted: {1.0: '100%'}
Actual: 0.0. Predicted: {0.0: '100%'}
Actual: 1.0. Predicted: {1.0: '100%'}
Actual: 2.0. Predicted: {1.0: '100%'}
Actual: 2.0. Predicted: {2.0: '100%'}
Actual: 0.0. Predicted: {0.0: '100%'}
Actual: 0.0. Predicted: {0.0: '100%'}
Actual: 2.0. Predicted: {2.0: '100%'}
Actual: 2.0. Predicted: {2.0: '100%'}
Actual: 2.0. Predicted: {2.0: '100%'}
Actual: 0.0. Predicted: {0.0: '100%'}
Actual: 2.0. Predicted: {2.0: '100%'}
Actual: 1.0. Predicted: {1.0: '100%'}
Actual: 2.0. Predicted: {2.0: '100%'}
Actual: 1.0. Predicted: {1.0: '100%'}
Actual: 2.0. Predicted: {1.0: '100%'}
Actual: 0.0. Predicted: {0.0: '100%'}
Actual: 1.0. Predicted: {1.0: '100%'}
Actual: 2.0. Predicted: {2.0: '100%'}
Actual: 0.0. Predicted: {0.0: '100%'}
Actual: 0.0. Predicted: {0.0: '100%'}
Actual: 2.0. Predicted: {2.0: '100%'}
Actual: 0.0. Predicted: {0.0: '100%'}
Actual: 2.0. Predicted: {1.0: '100%'}
Actual: 2.0. Predicted: {1.0: '100%'}
Actual: 1.0.